//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.CarDataUpdate.HtmlBuilder.com.bitauto.baa.api2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="impressionServiceSoap", Namespace="http://tempuri.org/")]
    public partial class impressionService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private ApiSoapHeader apiSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetLastestImpressionListBySerialIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetImpressionListBySerialIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public impressionService() {
            this.Url = global::BitAuto.CarDataUpdate.HtmlBuilder.Properties.Settings.Default.HtmlBuilder_com_bitauto_baa_api2_impressionService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public ApiSoapHeader ApiSoapHeaderValue {
            get {
                return this.apiSoapHeaderValueField;
            }
            set {
                this.apiSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLastestImpressionListBySerialIdCompletedEventHandler GetLastestImpressionListBySerialIdCompleted;
        
        /// <remarks/>
        public event GetImpressionListBySerialIdCompletedEventHandler GetImpressionListBySerialIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApiSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastestImpressionListBySerialId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLastestImpressionListBySerialId(int serialId, int pageIndex, int pageSize, out long recordCount) {
            object[] results = this.Invoke("GetLastestImpressionListBySerialId", new object[] {
                        serialId,
                        pageIndex,
                        pageSize});
            recordCount = ((long)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastestImpressionListBySerialIdAsync(int serialId, int pageIndex, int pageSize) {
            this.GetLastestImpressionListBySerialIdAsync(serialId, pageIndex, pageSize, null);
        }
        
        /// <remarks/>
        public void GetLastestImpressionListBySerialIdAsync(int serialId, int pageIndex, int pageSize, object userState) {
            if ((this.GetLastestImpressionListBySerialIdOperationCompleted == null)) {
                this.GetLastestImpressionListBySerialIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastestImpressionListBySerialIdOperationCompleted);
            }
            this.InvokeAsync("GetLastestImpressionListBySerialId", new object[] {
                        serialId,
                        pageIndex,
                        pageSize}, this.GetLastestImpressionListBySerialIdOperationCompleted, userState);
        }
        
        private void OnGetLastestImpressionListBySerialIdOperationCompleted(object arg) {
            if ((this.GetLastestImpressionListBySerialIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastestImpressionListBySerialIdCompleted(this, new GetLastestImpressionListBySerialIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ApiSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetImpressionListBySerialId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetImpressionListBySerialId(int serialId, int yuYi, int pageIndex, int pageSize, out long recordCount) {
            object[] results = this.Invoke("GetImpressionListBySerialId", new object[] {
                        serialId,
                        yuYi,
                        pageIndex,
                        pageSize});
            recordCount = ((long)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetImpressionListBySerialIdAsync(int serialId, int yuYi, int pageIndex, int pageSize) {
            this.GetImpressionListBySerialIdAsync(serialId, yuYi, pageIndex, pageSize, null);
        }
        
        /// <remarks/>
        public void GetImpressionListBySerialIdAsync(int serialId, int yuYi, int pageIndex, int pageSize, object userState) {
            if ((this.GetImpressionListBySerialIdOperationCompleted == null)) {
                this.GetImpressionListBySerialIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetImpressionListBySerialIdOperationCompleted);
            }
            this.InvokeAsync("GetImpressionListBySerialId", new object[] {
                        serialId,
                        yuYi,
                        pageIndex,
                        pageSize}, this.GetImpressionListBySerialIdOperationCompleted, userState);
        }
        
        private void OnGetImpressionListBySerialIdOperationCompleted(object arg) {
            if ((this.GetImpressionListBySerialIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetImpressionListBySerialIdCompleted(this, new GetImpressionListBySerialIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class ApiSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string appKeyField;
        
        private string appPwdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string AppKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
            }
        }
        
        /// <remarks/>
        public string AppPwd {
            get {
                return this.appPwdField;
            }
            set {
                this.appPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetLastestImpressionListBySerialIdCompletedEventHandler(object sender, GetLastestImpressionListBySerialIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastestImpressionListBySerialIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastestImpressionListBySerialIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public long recordCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetImpressionListBySerialIdCompletedEventHandler(object sender, GetImpressionListBySerialIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetImpressionListBySerialIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetImpressionListBySerialIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public long recordCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591