//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.CarDataUpdate.DataProcesser.cn.ucar.api.CarPrice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CarPriceSoap", Namespace="http://tempuri.org/")]
    public partial class CarPrice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPriceRangeByCarIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPriceRangeByCsIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPriceRangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCarTypePriceRangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CarPrice() {
            this.Url = global::BitAuto.CarDataUpdate.DataProcesser.Properties.Settings.Default.DataProcesser_cn_ucar_api_CarPrice_CarPrice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPriceRangeByCarIdCompletedEventHandler GetPriceRangeByCarIdCompleted;
        
        /// <remarks/>
        public event GetPriceRangeByCsIdCompletedEventHandler GetPriceRangeByCsIdCompleted;
        
        /// <remarks/>
        public event GetAllPriceRangeCompletedEventHandler GetAllPriceRangeCompleted;
        
        /// <remarks/>
        public event GetCarTypePriceRangeCompletedEventHandler GetCarTypePriceRangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPriceRangeByCarId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPriceRangeByCarId(int carId) {
            object[] results = this.Invoke("GetPriceRangeByCarId", new object[] {
                        carId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPriceRangeByCarIdAsync(int carId) {
            this.GetPriceRangeByCarIdAsync(carId, null);
        }
        
        /// <remarks/>
        public void GetPriceRangeByCarIdAsync(int carId, object userState) {
            if ((this.GetPriceRangeByCarIdOperationCompleted == null)) {
                this.GetPriceRangeByCarIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPriceRangeByCarIdOperationCompleted);
            }
            this.InvokeAsync("GetPriceRangeByCarId", new object[] {
                        carId}, this.GetPriceRangeByCarIdOperationCompleted, userState);
        }
        
        private void OnGetPriceRangeByCarIdOperationCompleted(object arg) {
            if ((this.GetPriceRangeByCarIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPriceRangeByCarIdCompleted(this, new GetPriceRangeByCarIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPriceRangeByCsId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPriceRangeByCsId(int csId) {
            object[] results = this.Invoke("GetPriceRangeByCsId", new object[] {
                        csId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPriceRangeByCsIdAsync(int csId) {
            this.GetPriceRangeByCsIdAsync(csId, null);
        }
        
        /// <remarks/>
        public void GetPriceRangeByCsIdAsync(int csId, object userState) {
            if ((this.GetPriceRangeByCsIdOperationCompleted == null)) {
                this.GetPriceRangeByCsIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPriceRangeByCsIdOperationCompleted);
            }
            this.InvokeAsync("GetPriceRangeByCsId", new object[] {
                        csId}, this.GetPriceRangeByCsIdOperationCompleted, userState);
        }
        
        private void OnGetPriceRangeByCsIdOperationCompleted(object arg) {
            if ((this.GetPriceRangeByCsIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPriceRangeByCsIdCompleted(this, new GetPriceRangeByCsIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllPriceRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllPriceRange() {
            object[] results = this.Invoke("GetAllPriceRange", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPriceRangeAsync() {
            this.GetAllPriceRangeAsync(null);
        }
        
        /// <remarks/>
        public void GetAllPriceRangeAsync(object userState) {
            if ((this.GetAllPriceRangeOperationCompleted == null)) {
                this.GetAllPriceRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPriceRangeOperationCompleted);
            }
            this.InvokeAsync("GetAllPriceRange", new object[0], this.GetAllPriceRangeOperationCompleted, userState);
        }
        
        private void OnGetAllPriceRangeOperationCompleted(object arg) {
            if ((this.GetAllPriceRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPriceRangeCompleted(this, new GetAllPriceRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCarTypePriceRange", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCarTypePriceRange(int serialId, int carYearType) {
            object[] results = this.Invoke("GetCarTypePriceRange", new object[] {
                        serialId,
                        carYearType});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCarTypePriceRangeAsync(int serialId, int carYearType) {
            this.GetCarTypePriceRangeAsync(serialId, carYearType, null);
        }
        
        /// <remarks/>
        public void GetCarTypePriceRangeAsync(int serialId, int carYearType, object userState) {
            if ((this.GetCarTypePriceRangeOperationCompleted == null)) {
                this.GetCarTypePriceRangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCarTypePriceRangeOperationCompleted);
            }
            this.InvokeAsync("GetCarTypePriceRange", new object[] {
                        serialId,
                        carYearType}, this.GetCarTypePriceRangeOperationCompleted, userState);
        }
        
        private void OnGetCarTypePriceRangeOperationCompleted(object arg) {
            if ((this.GetCarTypePriceRangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCarTypePriceRangeCompleted(this, new GetCarTypePriceRangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPriceRangeByCarIdCompletedEventHandler(object sender, GetPriceRangeByCarIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPriceRangeByCarIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPriceRangeByCarIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPriceRangeByCsIdCompletedEventHandler(object sender, GetPriceRangeByCsIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPriceRangeByCsIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPriceRangeByCsIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetAllPriceRangeCompletedEventHandler(object sender, GetAllPriceRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPriceRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPriceRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCarTypePriceRangeCompletedEventHandler(object sender, GetCarTypePriceRangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCarTypePriceRangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCarTypePriceRangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591