//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BitAuto.CarDataUpdate.DataProcesser.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.dealer.bitauto.com/api/Service/VendorInfor.asmx")]
        public string DataProcesser_com_bitauto_dealer_api_VendorInfor {
            get {
                return ((string)(this["DataProcesser_com_bitauto_dealer_api_VendorInfor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://news.bitauto.com/comment/newsservice.asmx")]
        public string DataProcesser_com_bitauto_news_NewsService {
            get {
                return ((string)(this["DataProcesser_com_bitauto_news_NewsService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.baa.bitauto.com/forumservice.asmx")]
        public string DataProcesser_cn_com_baa_api_ForumService {
            get {
                return ((string)(this["DataProcesser_cn_com_baa_api_ForumService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.dealer.bitauto.com/api/Service/VendorNews.asmx")]
        public string DataProcesser_com_bitauto_dealer_api1_VendorNews {
            get {
                return ((string)(this["DataProcesser_com_bitauto_dealer_api1_VendorNews"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://imgsvr.bitauto.com/common/commonservice.asmx")]
        public string DataProcesser_com_bitauto_imgsvr_CommonService {
            get {
                return ((string)(this["DataProcesser_com_bitauto_imgsvr_CommonService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://price.bitauto.com/interface/common/maintainservice.asmx")]
        public string DataProcesser_com_bitauto_price_MaintainService {
            get {
                return ((string)(this["DataProcesser_com_bitauto_price_MaintainService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.dealer.bitauto.com/api/Service/VendorInfor.asmx")]
        public string DataProcesser_com_bitauto_dealer_api1_VendorInfor {
            get {
                return ((string)(this["DataProcesser_com_bitauto_dealer_api1_VendorInfor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://yicheapi.taoche.cn/CarBasicIno/ForXml/CarPrice.asmx")]
        public string DataProcesser_cn_ucar_api_CarPrice_CarPrice {
            get {
                return ((string)(this["DataProcesser_cn_ucar_api_CarPrice_CarPrice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.taoche.cn/CarSourceInterface/CarSourceForBitAuto.asmx")]
        public string DataProcesser_cn_ucar_api_CarSourceForBitAuto {
            get {
                return ((string)(this["DataProcesser_cn_ucar_api_CarSourceForBitAuto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.dealer.bitauto.com/api/Service/ReplaceNews.asmx")]
        public string DataProcesser_com_bitauto_dealer_api_ReplaceNews_ReplaceNews {
            get {
                return ((string)(this["DataProcesser_com_bitauto_dealer_api_ReplaceNews_ReplaceNews"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.dealer.bitauto.com/api/Service/GetFavourableNews.asmx")]
        public string DataProcesser_com_bitauto_dealer_api_jiangjia_GetFavourableNews {
            get {
                return ((string)(this["DataProcesser_com_bitauto_dealer_api_jiangjia_GetFavourableNews"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api2.easypass.cn/indexapi/Service/IndexData.asmx")]
        public string DataProcesser_com_bitauto_index_IndexData {
            get {
                return ((string)(this["DataProcesser_com_bitauto_index_IndexData"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://carser.bitauto.com/ForPicMasterToSerial/service.asmx")]
        public string DataProcesser_com_bitauto_carser_Service {
            get {
                return ((string)(this["DataProcesser_com_bitauto_carser_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://api.baa.bitauto.com/koubei/usercar/userCarService.asmx")]
        public string DataProcesser_com_bitauto_baa_api_userCarService {
            get {
                return ((string)(this["DataProcesser_com_bitauto_baa_api_userCarService"]));
            }
        }
    }
}
