//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.CarDataUpdate.DataProcesser.com.bitauto.news {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NewsServiceSoap", Namespace="http://news.bitauto.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBaseCore))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Article[]))]
    public partial class NewsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetComentDataForNewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncNewsTitleOperationCompleted;
        
        private System.Threading.SendOrPostCallback SyncNewsTitleAndUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDailyTopNewsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWeeklyTopNewsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMonthlyTopNewsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPeriodTimeTopNewsListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SortNewsByCommentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SortTopNewsByCommentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateNewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateNewsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateCommentGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCommentGroupsByCommentableIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCommentGroupOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopNewsByOpinionWeeklyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopNewsByAgreeCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTopNewsByOpposeCountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NewsService() {
            this.Url = global::BitAuto.CarDataUpdate.DataProcesser.Properties.Settings.Default.DataProcesser_com_bitauto_news_NewsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetComentDataForNewsCompletedEventHandler GetComentDataForNewsCompleted;
        
        /// <remarks/>
        public event SyncNewsTitleCompletedEventHandler SyncNewsTitleCompleted;
        
        /// <remarks/>
        public event SyncNewsTitleAndUrlCompletedEventHandler SyncNewsTitleAndUrlCompleted;
        
        /// <remarks/>
        public event GetDailyTopNewsListCompletedEventHandler GetDailyTopNewsListCompleted;
        
        /// <remarks/>
        public event GetWeeklyTopNewsListCompletedEventHandler GetWeeklyTopNewsListCompleted;
        
        /// <remarks/>
        public event GetMonthlyTopNewsListCompletedEventHandler GetMonthlyTopNewsListCompleted;
        
        /// <remarks/>
        public event GetPeriodTimeTopNewsListCompletedEventHandler GetPeriodTimeTopNewsListCompleted;
        
        /// <remarks/>
        public event SortNewsByCommentsCompletedEventHandler SortNewsByCommentsCompleted;
        
        /// <remarks/>
        public event SortTopNewsByCommentsCompletedEventHandler SortTopNewsByCommentsCompleted;
        
        /// <remarks/>
        public event CreateNewsCompletedEventHandler CreateNewsCompleted;
        
        /// <remarks/>
        public event UpdateNewsCompletedEventHandler UpdateNewsCompleted;
        
        /// <remarks/>
        public event CreateCommentGroupCompletedEventHandler CreateCommentGroupCompleted;
        
        /// <remarks/>
        public event GetCommentGroupsByCommentableIDCompletedEventHandler GetCommentGroupsByCommentableIDCompleted;
        
        /// <remarks/>
        public event DeleteCommentGroupCompletedEventHandler DeleteCommentGroupCompleted;
        
        /// <remarks/>
        public event GetTopNewsByOpinionWeeklyCompletedEventHandler GetTopNewsByOpinionWeeklyCompleted;
        
        /// <remarks/>
        public event GetTopNewsByAgreeCountCompletedEventHandler GetTopNewsByAgreeCountCompleted;
        
        /// <remarks/>
        public event GetTopNewsByOpposeCountCompletedEventHandler GetTopNewsByOpposeCountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/GetComentDataForNews", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Article[] GetComentDataForNews(string words, int count) {
            object[] results = this.Invoke("GetComentDataForNews", new object[] {
                        words,
                        count});
            return ((Article[])(results[0]));
        }
        
        /// <remarks/>
        public void GetComentDataForNewsAsync(string words, int count) {
            this.GetComentDataForNewsAsync(words, count, null);
        }
        
        /// <remarks/>
        public void GetComentDataForNewsAsync(string words, int count, object userState) {
            if ((this.GetComentDataForNewsOperationCompleted == null)) {
                this.GetComentDataForNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetComentDataForNewsOperationCompleted);
            }
            this.InvokeAsync("GetComentDataForNews", new object[] {
                        words,
                        count}, this.GetComentDataForNewsOperationCompleted, userState);
        }
        
        private void OnGetComentDataForNewsOperationCompleted(object arg) {
            if ((this.GetComentDataForNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetComentDataForNewsCompleted(this, new GetComentDataForNewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/SyncNewsTitle", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SyncNewsTitle(int newsId, string title, string seckey) {
            object[] results = this.Invoke("SyncNewsTitle", new object[] {
                        newsId,
                        title,
                        seckey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SyncNewsTitleAsync(int newsId, string title, string seckey) {
            this.SyncNewsTitleAsync(newsId, title, seckey, null);
        }
        
        /// <remarks/>
        public void SyncNewsTitleAsync(int newsId, string title, string seckey, object userState) {
            if ((this.SyncNewsTitleOperationCompleted == null)) {
                this.SyncNewsTitleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncNewsTitleOperationCompleted);
            }
            this.InvokeAsync("SyncNewsTitle", new object[] {
                        newsId,
                        title,
                        seckey}, this.SyncNewsTitleOperationCompleted, userState);
        }
        
        private void OnSyncNewsTitleOperationCompleted(object arg) {
            if ((this.SyncNewsTitleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncNewsTitleCompleted(this, new SyncNewsTitleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/SyncNewsTitleAndUrl", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SyncNewsTitleAndUrl(int newsId, string title, string url, string seckey) {
            object[] results = this.Invoke("SyncNewsTitleAndUrl", new object[] {
                        newsId,
                        title,
                        url,
                        seckey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SyncNewsTitleAndUrlAsync(int newsId, string title, string url, string seckey) {
            this.SyncNewsTitleAndUrlAsync(newsId, title, url, seckey, null);
        }
        
        /// <remarks/>
        public void SyncNewsTitleAndUrlAsync(int newsId, string title, string url, string seckey, object userState) {
            if ((this.SyncNewsTitleAndUrlOperationCompleted == null)) {
                this.SyncNewsTitleAndUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSyncNewsTitleAndUrlOperationCompleted);
            }
            this.InvokeAsync("SyncNewsTitleAndUrl", new object[] {
                        newsId,
                        title,
                        url,
                        seckey}, this.SyncNewsTitleAndUrlOperationCompleted, userState);
        }
        
        private void OnSyncNewsTitleAndUrlOperationCompleted(object arg) {
            if ((this.SyncNewsTitleAndUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SyncNewsTitleAndUrlCompleted(this, new SyncNewsTitleAndUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/GetDailyTopNewsList", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetDailyTopNewsList(System.DateTime day, int count) {
            object[] results = this.Invoke("GetDailyTopNewsList", new object[] {
                        day,
                        count});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetDailyTopNewsListAsync(System.DateTime day, int count) {
            this.GetDailyTopNewsListAsync(day, count, null);
        }
        
        /// <remarks/>
        public void GetDailyTopNewsListAsync(System.DateTime day, int count, object userState) {
            if ((this.GetDailyTopNewsListOperationCompleted == null)) {
                this.GetDailyTopNewsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDailyTopNewsListOperationCompleted);
            }
            this.InvokeAsync("GetDailyTopNewsList", new object[] {
                        day,
                        count}, this.GetDailyTopNewsListOperationCompleted, userState);
        }
        
        private void OnGetDailyTopNewsListOperationCompleted(object arg) {
            if ((this.GetDailyTopNewsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDailyTopNewsListCompleted(this, new GetDailyTopNewsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/GetWeeklyTopNewsList", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetWeeklyTopNewsList(System.DateTime firstDayOfWeek, int count) {
            object[] results = this.Invoke("GetWeeklyTopNewsList", new object[] {
                        firstDayOfWeek,
                        count});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetWeeklyTopNewsListAsync(System.DateTime firstDayOfWeek, int count) {
            this.GetWeeklyTopNewsListAsync(firstDayOfWeek, count, null);
        }
        
        /// <remarks/>
        public void GetWeeklyTopNewsListAsync(System.DateTime firstDayOfWeek, int count, object userState) {
            if ((this.GetWeeklyTopNewsListOperationCompleted == null)) {
                this.GetWeeklyTopNewsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWeeklyTopNewsListOperationCompleted);
            }
            this.InvokeAsync("GetWeeklyTopNewsList", new object[] {
                        firstDayOfWeek,
                        count}, this.GetWeeklyTopNewsListOperationCompleted, userState);
        }
        
        private void OnGetWeeklyTopNewsListOperationCompleted(object arg) {
            if ((this.GetWeeklyTopNewsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWeeklyTopNewsListCompleted(this, new GetWeeklyTopNewsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/GetMonthlyTopNewsList", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetMonthlyTopNewsList(System.DateTime firstDayOfMonth, int count) {
            object[] results = this.Invoke("GetMonthlyTopNewsList", new object[] {
                        firstDayOfMonth,
                        count});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetMonthlyTopNewsListAsync(System.DateTime firstDayOfMonth, int count) {
            this.GetMonthlyTopNewsListAsync(firstDayOfMonth, count, null);
        }
        
        /// <remarks/>
        public void GetMonthlyTopNewsListAsync(System.DateTime firstDayOfMonth, int count, object userState) {
            if ((this.GetMonthlyTopNewsListOperationCompleted == null)) {
                this.GetMonthlyTopNewsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMonthlyTopNewsListOperationCompleted);
            }
            this.InvokeAsync("GetMonthlyTopNewsList", new object[] {
                        firstDayOfMonth,
                        count}, this.GetMonthlyTopNewsListOperationCompleted, userState);
        }
        
        private void OnGetMonthlyTopNewsListOperationCompleted(object arg) {
            if ((this.GetMonthlyTopNewsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMonthlyTopNewsListCompleted(this, new GetMonthlyTopNewsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/GetPeriodTimeTopNewsList", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetPeriodTimeTopNewsList([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> fromDate, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<System.DateTime> toDate, int count) {
            object[] results = this.Invoke("GetPeriodTimeTopNewsList", new object[] {
                        fromDate,
                        toDate,
                        count});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetPeriodTimeTopNewsListAsync(System.Nullable<System.DateTime> fromDate, System.Nullable<System.DateTime> toDate, int count) {
            this.GetPeriodTimeTopNewsListAsync(fromDate, toDate, count, null);
        }
        
        /// <remarks/>
        public void GetPeriodTimeTopNewsListAsync(System.Nullable<System.DateTime> fromDate, System.Nullable<System.DateTime> toDate, int count, object userState) {
            if ((this.GetPeriodTimeTopNewsListOperationCompleted == null)) {
                this.GetPeriodTimeTopNewsListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPeriodTimeTopNewsListOperationCompleted);
            }
            this.InvokeAsync("GetPeriodTimeTopNewsList", new object[] {
                        fromDate,
                        toDate,
                        count}, this.GetPeriodTimeTopNewsListOperationCompleted, userState);
        }
        
        private void OnGetPeriodTimeTopNewsListOperationCompleted(object arg) {
            if ((this.GetPeriodTimeTopNewsListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPeriodTimeTopNewsListCompleted(this, new GetPeriodTimeTopNewsListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/SortNewsByComments", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SortNewsByComments(int[] newsIDs) {
            object[] results = this.Invoke("SortNewsByComments", new object[] {
                        newsIDs});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SortNewsByCommentsAsync(int[] newsIDs) {
            this.SortNewsByCommentsAsync(newsIDs, null);
        }
        
        /// <remarks/>
        public void SortNewsByCommentsAsync(int[] newsIDs, object userState) {
            if ((this.SortNewsByCommentsOperationCompleted == null)) {
                this.SortNewsByCommentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSortNewsByCommentsOperationCompleted);
            }
            this.InvokeAsync("SortNewsByComments", new object[] {
                        newsIDs}, this.SortNewsByCommentsOperationCompleted, userState);
        }
        
        private void OnSortNewsByCommentsOperationCompleted(object arg) {
            if ((this.SortNewsByCommentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SortNewsByCommentsCompleted(this, new SortNewsByCommentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/SortTopNewsByComments", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable SortTopNewsByComments(int count, int[] newsIDs) {
            object[] results = this.Invoke("SortTopNewsByComments", new object[] {
                        count,
                        newsIDs});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void SortTopNewsByCommentsAsync(int count, int[] newsIDs) {
            this.SortTopNewsByCommentsAsync(count, newsIDs, null);
        }
        
        /// <remarks/>
        public void SortTopNewsByCommentsAsync(int count, int[] newsIDs, object userState) {
            if ((this.SortTopNewsByCommentsOperationCompleted == null)) {
                this.SortTopNewsByCommentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSortTopNewsByCommentsOperationCompleted);
            }
            this.InvokeAsync("SortTopNewsByComments", new object[] {
                        count,
                        newsIDs}, this.SortTopNewsByCommentsOperationCompleted, userState);
        }
        
        private void OnSortTopNewsByCommentsOperationCompleted(object arg) {
            if ((this.SortTopNewsByCommentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SortTopNewsByCommentsCompleted(this, new SortTopNewsByCommentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/CreateNews", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateNews(ArticleInfo news, string seckey, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> aliasNewsID, int[] sharedNewsIDs) {
            object[] results = this.Invoke("CreateNews", new object[] {
                        news,
                        seckey,
                        aliasNewsID,
                        sharedNewsIDs});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateNewsAsync(ArticleInfo news, string seckey, System.Nullable<int> aliasNewsID, int[] sharedNewsIDs) {
            this.CreateNewsAsync(news, seckey, aliasNewsID, sharedNewsIDs, null);
        }
        
        /// <remarks/>
        public void CreateNewsAsync(ArticleInfo news, string seckey, System.Nullable<int> aliasNewsID, int[] sharedNewsIDs, object userState) {
            if ((this.CreateNewsOperationCompleted == null)) {
                this.CreateNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateNewsOperationCompleted);
            }
            this.InvokeAsync("CreateNews", new object[] {
                        news,
                        seckey,
                        aliasNewsID,
                        sharedNewsIDs}, this.CreateNewsOperationCompleted, userState);
        }
        
        private void OnCreateNewsOperationCompleted(object arg) {
            if ((this.CreateNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateNewsCompleted(this, new CreateNewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/UpdateNews", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateNews(ArticleInfo news, string seckey) {
            object[] results = this.Invoke("UpdateNews", new object[] {
                        news,
                        seckey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateNewsAsync(ArticleInfo news, string seckey) {
            this.UpdateNewsAsync(news, seckey, null);
        }
        
        /// <remarks/>
        public void UpdateNewsAsync(ArticleInfo news, string seckey, object userState) {
            if ((this.UpdateNewsOperationCompleted == null)) {
                this.UpdateNewsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateNewsOperationCompleted);
            }
            this.InvokeAsync("UpdateNews", new object[] {
                        news,
                        seckey}, this.UpdateNewsOperationCompleted, userState);
        }
        
        private void OnUpdateNewsOperationCompleted(object arg) {
            if ((this.UpdateNewsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateNewsCompleted(this, new UpdateNewsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/CreateCommentGroup", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateCommentGroup(GroupRelation commentGroup, string seckey) {
            object[] results = this.Invoke("CreateCommentGroup", new object[] {
                        commentGroup,
                        seckey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateCommentGroupAsync(GroupRelation commentGroup, string seckey) {
            this.CreateCommentGroupAsync(commentGroup, seckey, null);
        }
        
        /// <remarks/>
        public void CreateCommentGroupAsync(GroupRelation commentGroup, string seckey, object userState) {
            if ((this.CreateCommentGroupOperationCompleted == null)) {
                this.CreateCommentGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateCommentGroupOperationCompleted);
            }
            this.InvokeAsync("CreateCommentGroup", new object[] {
                        commentGroup,
                        seckey}, this.CreateCommentGroupOperationCompleted, userState);
        }
        
        private void OnCreateCommentGroupOperationCompleted(object arg) {
            if ((this.CreateCommentGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCommentGroupCompleted(this, new CreateCommentGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/GetCommentGroupsByCommentableID", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public GroupRelation[] GetCommentGroupsByCommentableID(int commentableID, int commentableType) {
            object[] results = this.Invoke("GetCommentGroupsByCommentableID", new object[] {
                        commentableID,
                        commentableType});
            return ((GroupRelation[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCommentGroupsByCommentableIDAsync(int commentableID, int commentableType) {
            this.GetCommentGroupsByCommentableIDAsync(commentableID, commentableType, null);
        }
        
        /// <remarks/>
        public void GetCommentGroupsByCommentableIDAsync(int commentableID, int commentableType, object userState) {
            if ((this.GetCommentGroupsByCommentableIDOperationCompleted == null)) {
                this.GetCommentGroupsByCommentableIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCommentGroupsByCommentableIDOperationCompleted);
            }
            this.InvokeAsync("GetCommentGroupsByCommentableID", new object[] {
                        commentableID,
                        commentableType}, this.GetCommentGroupsByCommentableIDOperationCompleted, userState);
        }
        
        private void OnGetCommentGroupsByCommentableIDOperationCompleted(object arg) {
            if ((this.GetCommentGroupsByCommentableIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCommentGroupsByCommentableIDCompleted(this, new GetCommentGroupsByCommentableIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/DeleteCommentGroup", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteCommentGroup(GroupRelation commentGroup, string seckey) {
            object[] results = this.Invoke("DeleteCommentGroup", new object[] {
                        commentGroup,
                        seckey});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCommentGroupAsync(GroupRelation commentGroup, string seckey) {
            this.DeleteCommentGroupAsync(commentGroup, seckey, null);
        }
        
        /// <remarks/>
        public void DeleteCommentGroupAsync(GroupRelation commentGroup, string seckey, object userState) {
            if ((this.DeleteCommentGroupOperationCompleted == null)) {
                this.DeleteCommentGroupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCommentGroupOperationCompleted);
            }
            this.InvokeAsync("DeleteCommentGroup", new object[] {
                        commentGroup,
                        seckey}, this.DeleteCommentGroupOperationCompleted, userState);
        }
        
        private void OnDeleteCommentGroupOperationCompleted(object arg) {
            if ((this.DeleteCommentGroupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCommentGroupCompleted(this, new DeleteCommentGroupCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/GetTopNewsByOpinionWeekly", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTopNewsByOpinionWeekly(OpinionType opinion, int pageSize, int pageIndex, int[] categoryIDs, out int totalRecords) {
            object[] results = this.Invoke("GetTopNewsByOpinionWeekly", new object[] {
                        opinion,
                        pageSize,
                        pageIndex,
                        categoryIDs});
            totalRecords = ((int)(results[1]));
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopNewsByOpinionWeeklyAsync(OpinionType opinion, int pageSize, int pageIndex, int[] categoryIDs) {
            this.GetTopNewsByOpinionWeeklyAsync(opinion, pageSize, pageIndex, categoryIDs, null);
        }
        
        /// <remarks/>
        public void GetTopNewsByOpinionWeeklyAsync(OpinionType opinion, int pageSize, int pageIndex, int[] categoryIDs, object userState) {
            if ((this.GetTopNewsByOpinionWeeklyOperationCompleted == null)) {
                this.GetTopNewsByOpinionWeeklyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopNewsByOpinionWeeklyOperationCompleted);
            }
            this.InvokeAsync("GetTopNewsByOpinionWeekly", new object[] {
                        opinion,
                        pageSize,
                        pageIndex,
                        categoryIDs}, this.GetTopNewsByOpinionWeeklyOperationCompleted, userState);
        }
        
        private void OnGetTopNewsByOpinionWeeklyOperationCompleted(object arg) {
            if ((this.GetTopNewsByOpinionWeeklyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopNewsByOpinionWeeklyCompleted(this, new GetTopNewsByOpinionWeeklyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/GetTopNewsByAgreeCount", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTopNewsByAgreeCount(int count) {
            object[] results = this.Invoke("GetTopNewsByAgreeCount", new object[] {
                        count});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopNewsByAgreeCountAsync(int count) {
            this.GetTopNewsByAgreeCountAsync(count, null);
        }
        
        /// <remarks/>
        public void GetTopNewsByAgreeCountAsync(int count, object userState) {
            if ((this.GetTopNewsByAgreeCountOperationCompleted == null)) {
                this.GetTopNewsByAgreeCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopNewsByAgreeCountOperationCompleted);
            }
            this.InvokeAsync("GetTopNewsByAgreeCount", new object[] {
                        count}, this.GetTopNewsByAgreeCountOperationCompleted, userState);
        }
        
        private void OnGetTopNewsByAgreeCountOperationCompleted(object arg) {
            if ((this.GetTopNewsByAgreeCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopNewsByAgreeCountCompleted(this, new GetTopNewsByAgreeCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://news.bitauto.com/GetTopNewsByOpposeCount", RequestNamespace="http://news.bitauto.com/", ResponseNamespace="http://news.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTopNewsByOpposeCount(int count) {
            object[] results = this.Invoke("GetTopNewsByOpposeCount", new object[] {
                        count});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTopNewsByOpposeCountAsync(int count) {
            this.GetTopNewsByOpposeCountAsync(count, null);
        }
        
        /// <remarks/>
        public void GetTopNewsByOpposeCountAsync(int count, object userState) {
            if ((this.GetTopNewsByOpposeCountOperationCompleted == null)) {
                this.GetTopNewsByOpposeCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTopNewsByOpposeCountOperationCompleted);
            }
            this.InvokeAsync("GetTopNewsByOpposeCount", new object[] {
                        count}, this.GetTopNewsByOpposeCountOperationCompleted, userState);
        }
        
        private void OnGetTopNewsByOpposeCountOperationCompleted(object arg) {
            if ((this.GetTopNewsByOpposeCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTopNewsByOpposeCountCompleted(this, new GetTopNewsByOpposeCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public partial class Article : ArticleBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Article))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public abstract partial class ArticleBase : EntityBase {
        
        private int idField;
        
        private int originalIdField;
        
        private string titleField;
        
        private string urlField;
        
        private int commentCountField;
        
        private int partitionIdField;
        
        private int posterCountField;
        
        private System.DateTime createTimeField;
        
        private System.Nullable<int> carSerialField;
        
        private System.Nullable<System.DateTime> lastCommentTimeField;
        
        private System.Nullable<int> lastCommentIdField;
        
        private int articleTypeField;
        
        private int originalArticleTypeField;
        
        private System.Nullable<int> participationCountField;
        
        private System.Nullable<int> statusField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int OriginalId {
            get {
                return this.originalIdField;
            }
            set {
                this.originalIdField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public int CommentCount {
            get {
                return this.commentCountField;
            }
            set {
                this.commentCountField = value;
            }
        }
        
        /// <remarks/>
        public int PartitionId {
            get {
                return this.partitionIdField;
            }
            set {
                this.partitionIdField = value;
            }
        }
        
        /// <remarks/>
        public int PosterCount {
            get {
                return this.posterCountField;
            }
            set {
                this.posterCountField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime CreateTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CarSerial {
            get {
                return this.carSerialField;
            }
            set {
                this.carSerialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastCommentTime {
            get {
                return this.lastCommentTimeField;
            }
            set {
                this.lastCommentTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> LastCommentId {
            get {
                return this.lastCommentIdField;
            }
            set {
                this.lastCommentIdField = value;
            }
        }
        
        /// <remarks/>
        public int ArticleType {
            get {
                return this.articleTypeField;
            }
            set {
                this.articleTypeField = value;
            }
        }
        
        /// <remarks/>
        public int OriginalArticleType {
            get {
                return this.originalArticleTypeField;
            }
            set {
                this.originalArticleTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ParticipationCount {
            get {
                return this.participationCountField;
            }
            set {
                this.participationCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupRelationBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupRelation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArticleExpandBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArticleExpand))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArticleBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Article))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public abstract partial class EntityBase : EntityBaseCore {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupRelationBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupRelation))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArticleExpandBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArticleExpand))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArticleBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Article))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public abstract partial class EntityBaseCore {
        
        private object tagField;
        
        /// <remarks/>
        public object Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public partial class ArticleInfo {
        
        private Article articleField;
        
        private ArticleExpand articleExpandField;
        
        private GroupRelation[] commentGroupsField;
        
        /// <remarks/>
        public Article Article {
            get {
                return this.articleField;
            }
            set {
                this.articleField = value;
            }
        }
        
        /// <remarks/>
        public ArticleExpand ArticleExpand {
            get {
                return this.articleExpandField;
            }
            set {
                this.articleExpandField = value;
            }
        }
        
        /// <remarks/>
        public GroupRelation[] CommentGroups {
            get {
                return this.commentGroupsField;
            }
            set {
                this.commentGroupsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public partial class ArticleExpand : ArticleExpandBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ArticleExpand))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public abstract partial class ArticleExpandBase : EntityBase {
        
        private int articleTypeField;
        
        private int originalArticleTypeField;
        
        private int articleIdField;
        
        private int originalArticleIdField;
        
        private System.Nullable<int> categoryIdField;
        
        private string categoryTitleField;
        
        private System.Nullable<int> categoryTypeIdField;
        
        private string categoryTypeNameField;
        
        private System.Nullable<System.DateTime> startDateTimeField;
        
        private System.Nullable<System.DateTime> endDateTimeField;
        
        private string extendInfoField;
        
        /// <remarks/>
        public int ArticleType {
            get {
                return this.articleTypeField;
            }
            set {
                this.articleTypeField = value;
            }
        }
        
        /// <remarks/>
        public int OriginalArticleType {
            get {
                return this.originalArticleTypeField;
            }
            set {
                this.originalArticleTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ArticleId {
            get {
                return this.articleIdField;
            }
            set {
                this.articleIdField = value;
            }
        }
        
        /// <remarks/>
        public int OriginalArticleId {
            get {
                return this.originalArticleIdField;
            }
            set {
                this.originalArticleIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CategoryId {
            get {
                return this.categoryIdField;
            }
            set {
                this.categoryIdField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryTitle {
            get {
                return this.categoryTitleField;
            }
            set {
                this.categoryTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> CategoryTypeId {
            get {
                return this.categoryTypeIdField;
            }
            set {
                this.categoryTypeIdField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryTypeName {
            get {
                return this.categoryTypeNameField;
            }
            set {
                this.categoryTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDateTime {
            get {
                return this.startDateTimeField;
            }
            set {
                this.startDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDateTime {
            get {
                return this.endDateTimeField;
            }
            set {
                this.endDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ExtendInfo {
            get {
                return this.extendInfoField;
            }
            set {
                this.extendInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public partial class GroupRelation : GroupRelationBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GroupRelation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public abstract partial class GroupRelationBase : EntityBase {
        
        private int commentableIdField;
        
        private int originalCommentableIdField;
        
        private int groupIdField;
        
        private int commentableTypeField;
        
        private int originalCommentableTypeField;
        
        /// <remarks/>
        public int CommentableId {
            get {
                return this.commentableIdField;
            }
            set {
                this.commentableIdField = value;
            }
        }
        
        /// <remarks/>
        public int OriginalCommentableId {
            get {
                return this.originalCommentableIdField;
            }
            set {
                this.originalCommentableIdField = value;
            }
        }
        
        /// <remarks/>
        public int GroupId {
            get {
                return this.groupIdField;
            }
            set {
                this.groupIdField = value;
            }
        }
        
        /// <remarks/>
        public int CommentableType {
            get {
                return this.commentableTypeField;
            }
            set {
                this.commentableTypeField = value;
            }
        }
        
        /// <remarks/>
        public int OriginalCommentableType {
            get {
                return this.originalCommentableTypeField;
            }
            set {
                this.originalCommentableTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://news.bitauto.com/")]
    public enum OpinionType {
        
        /// <remarks/>
        Ding,
        
        /// <remarks/>
        HaoWen,
        
        /// <remarks/>
        QiangShou,
        
        /// <remarks/>
        LeiRen,
        
        /// <remarks/>
        Jiong,
        
        /// <remarks/>
        BiaoTiDang,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetComentDataForNewsCompletedEventHandler(object sender, GetComentDataForNewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetComentDataForNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetComentDataForNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Article[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Article[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SyncNewsTitleCompletedEventHandler(object sender, SyncNewsTitleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncNewsTitleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncNewsTitleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SyncNewsTitleAndUrlCompletedEventHandler(object sender, SyncNewsTitleAndUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SyncNewsTitleAndUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SyncNewsTitleAndUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetDailyTopNewsListCompletedEventHandler(object sender, GetDailyTopNewsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDailyTopNewsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDailyTopNewsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetWeeklyTopNewsListCompletedEventHandler(object sender, GetWeeklyTopNewsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWeeklyTopNewsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWeeklyTopNewsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMonthlyTopNewsListCompletedEventHandler(object sender, GetMonthlyTopNewsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMonthlyTopNewsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMonthlyTopNewsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetPeriodTimeTopNewsListCompletedEventHandler(object sender, GetPeriodTimeTopNewsListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPeriodTimeTopNewsListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPeriodTimeTopNewsListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SortNewsByCommentsCompletedEventHandler(object sender, SortNewsByCommentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SortNewsByCommentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SortNewsByCommentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SortTopNewsByCommentsCompletedEventHandler(object sender, SortTopNewsByCommentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SortTopNewsByCommentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SortTopNewsByCommentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateNewsCompletedEventHandler(object sender, CreateNewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateNewsCompletedEventHandler(object sender, UpdateNewsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateNewsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateNewsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateCommentGroupCompletedEventHandler(object sender, CreateCommentGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCommentGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCommentGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetCommentGroupsByCommentableIDCompletedEventHandler(object sender, GetCommentGroupsByCommentableIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCommentGroupsByCommentableIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCommentGroupsByCommentableIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GroupRelation[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GroupRelation[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void DeleteCommentGroupCompletedEventHandler(object sender, DeleteCommentGroupCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCommentGroupCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCommentGroupCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTopNewsByOpinionWeeklyCompletedEventHandler(object sender, GetTopNewsByOpinionWeeklyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopNewsByOpinionWeeklyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopNewsByOpinionWeeklyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int totalRecords {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTopNewsByAgreeCountCompletedEventHandler(object sender, GetTopNewsByAgreeCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopNewsByAgreeCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopNewsByAgreeCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTopNewsByOpposeCountCompletedEventHandler(object sender, GetTopNewsByOpposeCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTopNewsByOpposeCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTopNewsByOpposeCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591