//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18408 版自动生成。
// 
#pragma warning disable 1591

namespace BitAuto.CarDataUpdate.DataProcesser.com.bitauto.dealer.api.ReplaceNews {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ReplaceNewsSoap", Namespace="http://www.bitauto.com/")]
    public partial class ReplaceNews : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private DasSoapHeader dasSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback GetNewsListBySerialIDOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ReplaceNews() {
            this.Url = global::BitAuto.CarDataUpdate.DataProcesser.Properties.Settings.Default.DataProcesser_com_bitauto_dealer_api_ReplaceNews_ReplaceNews;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public DasSoapHeader DasSoapHeaderValue {
            get {
                return this.dasSoapHeaderValueField;
            }
            set {
                this.dasSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNewsListBySerialIDCompletedEventHandler GetNewsListBySerialIDCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("DasSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.bitauto.com/GetNewsListBySerialID", RequestNamespace="http://www.bitauto.com/", ResponseNamespace="http://www.bitauto.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetNewsListBySerialID(int BrandId) {
            object[] results = this.Invoke("GetNewsListBySerialID", new object[] {
                        BrandId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewsListBySerialIDAsync(int BrandId) {
            this.GetNewsListBySerialIDAsync(BrandId, null);
        }
        
        /// <remarks/>
        public void GetNewsListBySerialIDAsync(int BrandId, object userState) {
            if ((this.GetNewsListBySerialIDOperationCompleted == null)) {
                this.GetNewsListBySerialIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewsListBySerialIDOperationCompleted);
            }
            this.InvokeAsync("GetNewsListBySerialID", new object[] {
                        BrandId}, this.GetNewsListBySerialIDOperationCompleted, userState);
        }
        
        private void OnGetNewsListBySerialIDOperationCompleted(object arg) {
            if ((this.GetNewsListBySerialIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewsListBySerialIDCompleted(this, new GetNewsListBySerialIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bitauto.com/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bitauto.com/", IsNullable=false)]
    public partial class DasSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private System.Guid tokenKeyField;
        
        private string authorizeCodeField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public System.Guid TokenKey {
            get {
                return this.tokenKeyField;
            }
            set {
                this.tokenKeyField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorizeCode {
            get {
                return this.authorizeCodeField;
            }
            set {
                this.authorizeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetNewsListBySerialIDCompletedEventHandler(object sender, GetNewsListBySerialIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewsListBySerialIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewsListBySerialIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591